name: CD - Continuous Delivery and Deploy

on: 
    workflow_run:
        workflows: ["CI - Automated Tests"]
        types: 
            - completed
    push: 
        branches: ["pokemon-app-1.0"]

jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success'}}
        runs-on: ubuntu-latest

steps: 
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: 